# Generated by Django 3.0.14 on 2021-11-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('title', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=16)),
                ('award', models.CharField(max_length=6)),
                ('period1', models.DateField(max_length=14)),
                ('period2', models.DateField(max_length=14)),
                ('Participant', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('진행', 'doing'), ('예정', 'plan'), ('종료', 'end')], max_length=5)),
                ('tag_set', models.ManyToManyField(blank=True, to='challenges.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
